In [1]:
from delimited_test_to_csv import convert_csv

/home/ubuntu/anaconda3/envs/textseg/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/ubuntu/anaconda3/envs/textseg/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/ubuntu/anaconda3/envs/textseg/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/ubuntu/anaconda3/envs/textseg/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/ubuntu/anaconda3/envs

In [2]:
convert_csv('submission_12_epochs')

[nltk_data] Downloading package punkt to /home/ubuntu/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


2018-08-01 18:21:09,686 - INFO - No split for sentence with backslash n. Doc Id: test_123.txt   Sentence:  ********
Percent changes are based on the daily sales rate and reflect 24 selling days this month vs In a short sale investors borrow shares and sell them betting that the stock price will fall.


test_120.txt
[4 1 1 3]
length of sen
9
test_148.txt
[2 2 2 3]
length of sen
9
test_234.txt
[2 2 3 2]
length of sen
9
test_136.txt
[2 2 2 2]
length of sen
8
test_157.txt
[2 1 1 2 1]
length of sen
7
test_63.txt
[2 2 1 1 2]
length of sen
9
test_238.txt
[3 3 2 1]
length of sen
9
test_97.txt
[1 1 1 1]
length of sen
4
test_164.txt
[3 1 4 1]
length of sen
10
test_202.txt
[1 2 2 1 2]
length of sen
8
test_204.txt
[2 2 3]
length of sen
7
test_152.txt
[3 3 3 2]
length of sen
11
test_249.txt
[2 1 2 4 2]
length of sen
11
test_36.txt
[6 2 2 3 3]
length of sen
16
test_69.txt
[1 1 1 2]
length of sen
5
test_242.txt
[3 2 2 2]
length of sen
9
test_190.txt
[3 1 3 3]
length of sen
10
test_67.txt
[3 4 1 2]
length of sen
10
test_77.txt
[2 3 1 1 3]
length of sen
10
test_197.txt
[2 1 1 4 3]
length of sen
11
test_13.txt
[1 2 1 1]
length of sen
5
test_239.txt
[4 5 1 3 3]
length of sen
16
test_54.txt
[3 3 3 4]
length of sen
13
test_46.txt
[1 1 2 1 1 3]
length of sen
9
test_14.txt
[1 4 3 2]
length of sen
11
test_4

length of sen
8
test_211.txt
[2 2 3 2]
length of sen
9
test_88.txt
[1 1 2 4]
length of sen
8
test_30.txt
[1 1 2 2 2]
length of sen
8
test_151.txt
[2 3 2 2]
length of sen
9
test_17.txt
[2 3 1 1]
length of sen
7
test_28.txt
[2 2 2 1 1]
length of sen
8
test_175.txt
[1 1 2 2]
length of sen
6
test_217.txt
[1 2 3 2]
length of sen
8
